import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = inter.className;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font} relative `}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
