"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import { useUser, signOutFunction } from "../app/lib/auth";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = inter.className;

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const findPathname = pathname.includes("/course");
  console.log("pathname :", pathname, findPathname);
  return (
    <html lang="en">
      <body className={`${font} relative `}>
        {!findPathname ? <Navigation /> : null}
        {children}
      </body>
    </html>
  );
}
